bibata-build: Avoid failure with (the default) empty bibataJvmArgs
The manifestation is quite confusing:

    Error: Could not find or load main class
    Caused by: java.lang.ClassNotFoundException:

What really happens is "".split(' ') returns a list of 1 element – the empty
string.  It gets passed as one of the first arguments to the JVM which then
tries to load it as the main class.