RendererBackend: Don't refer to BatikRendererBackend directly
This causes the class to be initialized even when not used, and ultimately causes:

    java.lang.NoClassDefFoundError: org/apache/batik/transcoder/SVGAbstractTranscoder
            ...
            at io.github.stanio.mousegen.RendererBackend.<clinit>(RendererBackend.java:65)
            at io.github.stanio.mousegen.CursorRenderer.<init>(CursorRenderer.java:76)
            at io.github.stanio.mousegen.MouseGen.<init>(MouseGen.java:72)
            at io.github.stanio.mousegen.MouseGen.main(MouseGen.java:290)
            at io.github.stanio.mousegen.Command.main(Command.java:38)
    Caused by: java.lang.ClassNotFoundException: org.apache.batik.transcoder.SVGAbstractTranscoder
            ...

when the Batik libraries are not present.